### Add ticket
POST http://localhost:3003/api/tickets
Content-TYpe: application/json

{
    "app": "Mea",
    "priority": "H",
    "description": "Nightomea"
}

### Delete
DELETE http://localhost:3003/api/tickets/62b6c9dd983f8a595edcf65f
